version: "3.8"

services:
  shiki:
    image: drownself/shiki:0.1.0
    ports:
      - 5001:80
    environment: 
      - DiscordToken=YOUR_TOKEN
      - IpAdress=lavalink
      - Port=2333
      - LavalinkPassword=YOUR_PASSWORD
      - GeniusToken=YOUR_TOKEN
    networks:
      - lyrics-bridge
      - sound-bridge
    depends_on:
      - lavalink
      
  lavalink:
    image: fredboat/lavalink:latest
    environment:
      - SERVER_PORT=YOUR_PORT
      - LAVALINK_SERVER_BUFFER_DURATION_MS=400
      - LAVALINK_SERVER_PASSWORD=YOUR_PASSWORD
      - LAVALINK_SERVER_SOURCES_BANDCAMP=true
      - LAVALINK_SERVER_SOURCES_HTTP=true
      - LAVALINK_SERVER_SOURCES_MIXER=false
      - LAVALINK_SERVER_SOURCES_SOUNDCLOUD=true
      - LAVALINK_SERVER_SOURCES_TWITCH=false
      - LAVALINK_SERVER_SOURCES_VIMEO=false
      - LAVALINK_SERVER_SOURCES_YOUTUBE=true
    ports:
      - "2333:2333"
    networks:
      - sound-bridge
    expose:
      - 2333
  
  lyrics:
    image: pr1ncee/song_lyrics_parser:0.1.2
    ports:
      - "8000:8000"
    networks:
      - lyrics-bridge
    expose:
      - 8000
    
networks:
    sound-bridge:
        driver: bridge
    lyrics-bridge:
        driver: bridge
